#ifndef ANIMCHANNEL_HPP
#define ANIMCHANNEL_HPP

enum AnimChannel {
    ANIMCHANNEL_TX_BIT = 1,
    ANIMCHANNEL_TY_BIT = 2,
    ANIMCHANNEL_TZ_BIT = 4,
    ANIMCHANNEL_QX_BIT = 8,
    ANIMCHANNEL_QY_BIT = 16,
    ANIMCHANNEL_QZ_BIT = 32
};

#endif